### ISSUE TITLE
SubscriptionServer.create is not exists.

### ISSUE THREAD

**Issue by developerworks** [apollographql/subscriptions-transport-ws#145]
```
var subscriptionServer = _subscriptionsTransportWs.SubscriptionServer.create({
                                                                      ^

TypeError: _subscriptionsTransportWs.SubscriptionServer.create is not a function
    at Object.<anonymous> (/Users/hezhiqiang/totoro/agent_graphql_server/src/server/index.js:140:47)
    at Module._compile (module.js:571:32)
    at loader (/Users/hezhiqiang/totoro/agent_graphql_server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hezhiqiang/totoro/agent_graphql_server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/hezhiqiang/totoro/agent_graphql_server/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:571:32)
```

Seems like you have not publish the latest version, Latest version on npmjs.org is 0.6.0.

**Comment by mistic** [comment]
@developerworks `SubscriptionServer.create` is part of new version `0.7.0` that it's about to came out.

**Comment by Urigo** [comment]
0.7 is out now!
I'm closing but let me know if I should reopen in case it's still not working for you
