### ISSUE TITLE
TypeScript runtime error "TypeError: Cannot read property 'create' of undefined" for SubscriptionServer

### ISSUE THREAD

**Issue by rw3iss** [apollographql/subscriptions-transport-ws#564]
I'm on Windows, using WSL, trying to go through the simple example in the readme, and it compiles, but upon running produces the following error:

```
rw3iss@rw3iss:/mnt/c/Users/Ryan/Sites/rapi/api$ nodemon build/server.js --watch
[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node build/server.js`
webpack-internal:///./src/server.ts:64
subscriptions_transport_ws_1.SubscriptionServer.create({
                                                ^

TypeError: Cannot read property 'create' of undefined
    at Object.eval (webpack-internal:///./src/server.ts:64:49)
    at eval (webpack-internal:///./src/server.ts:73:30)
    at Object../src/server.ts (/mnt/c/Users/Ryan/Sites/rapi/api/build/server.js:1667:1)
    at __webpack_require__ (/mnt/c/Users/Ryan/Sites/rapi/api/build/server.js:20:30)
    at Object.0 (/mnt/c/Users/Ryan/Sites/rapi/api/build/server.js:1678:18)
    at __webpack_require__ (/mnt/c/Users/Ryan/Sites/rapi/api/build/server.js:20:30)
    at /mnt/c/Users/Ryan/Sites/rapi/api/build/server.js:84:18
    at Object.<anonymous> (/mnt/c/Users/Ryan/Sites/rapi/api/build/server.js:87:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
[nodemon] app crashed - waiting for file changes before starting...
```

I'm using TypeScript, ie:

```
import { SubscriptionServer } from 'subscriptions-transport-ws';
SubscriptionServer.create({...});
```

My tsconfig:
```
 "compilerOptions": {
        "incremental": true,
        "baseUrl": "./",
        "outDir": "./build/",       // path to output directory
        "sourceMap": true,          // allow sourcemap support
        "strictNullChecks": true,   // enable strict null checks as a best practice
        "module": "commonjs",            // specifiy module code generation
        "moduleResolution": "node",
        "target": "esnext",         // specify ECMAScript target version
        "allowJs": true,            // allow a partial TypeScript and JavaScript codebase  
        "noImplicitThis": true,
        "noImplicitReturns": true,
        "lib": [
            "ESNext.AsyncIterable"
        ]
    }
```

And also my webpack.config:
```
var config = {
    mode: 'development',
    entry: {
        server: [
            SRC_DIR + '/server.ts'
        ] 
    },
    target: 'node',
    output: {
        publicPath: '/',
        path: BUILD_DIR,
        filename: '[name].js'
    },
    resolve: {
        mainFields: ['browser', 'main', 'module'],
        extensions: ['.js', '.json', '.ts']
    },
    module: {
        rules: [
            { 
                test: /\.(t|j)s?$/, 
                include: [
                    SRC_DIR,
                    SHARED_DIR
                ],
                exclude: /node_modules/,
                loader: ['ts-loader']
            },
            {
                test: /\.mjs$/,
                include: /node_modules/,
                type: "javascript/auto",
              }
        ]
    },
};
module.exports = config;
```

Why would this property SubscriptionServer be null after the import? This is the way all of the examples are doing it, so I'm wondering if it's maybe a problem with my setup. Thanks.

**Comment by rw3iss** [comment]
Seems to have been fixed by modifying tsconfig.json:

```
        "module": "esnext",
        "moduleResolution": "node",
        "target": "es2018", 
        "strict": true,
        "lib": [
            "es6",
            "ESNext.AsyncIterable"
        ],
```

Not sure which of those did it exactly :-)
