### ISSUE TITLE
Cannot set property 'readyState' of undefined

### ISSUE THREAD

**Issue by AruXc** [apollographql/subscriptions-transport-ws#714]
subscriptions-transport-ws dependency of ws, but this is already missing 2 major version. 

this version make my server crash

[issue](https://github.com/moleculerjs/moleculer-apollo-server/issues/51)

subscriptions-transport-ws can update to 7.2?

```
  websocket.readyState = WebSocket.CLOSING;
                       ^

TypeError: Cannot set property 'readyState' of undefined
    at Socket.socketOnClose (/Users/aru/Desktop/WanFang/onecare_server/node_modules/ws/lib/websocket.js:757:24)
    at Socket.emit (events.js:194:15)
    at TCP._handle.close (net.js:597:12)
```

**Comment by Patrick-Spiegel** [comment]
This is still occuring, still no update?

**Comment by Suyashtnt** [comment]
I am also getting this issue,
Code:
```ts
//GQL
GQLServer.applyMiddleware({ app });
const server = createServer(app);
GQLServer.installSubscriptionHandlers(server);

server.listen(port, () => {
	new SubscriptionServer(
		{
			execute,
			subscribe,
			schema: buildSchema(typeDefs),
		},
		{
			server: server,
			path: '/graphql',
		},
	);
});
```

**Comment by mabc224** [comment]
+1
